# Generated by Django 5.2.18 on 2026-10-08 08:26

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0003_case_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsrcommunication',
            name='direction',
            field=models.CharField(choices=[('DPO_TO_PATIENT', 'DPO to patient'), ('PATIENT_TO_DPO', 'Patient to DPO')], default='DPO_TO_PATIENT', max_length=16),
        ),
        migrations.AddField(
            model_name='dsrrequest',
            name='escalated_from',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='dsrcaseevent',
            name='event_type',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('TASK_CREATED', 'Review task created'), ('TASK_UPDATED', 'Review task updated'), ('DECISION_RECORDED', 'Decision recorded'), ('PATIENT_UPDATE_RECORDED', 'Patient update recorded'), ('PATIENT_RESPONSE_RECORDED', 'Patient response recorded'), ('CASES_EXPORTED', 'Case included in a DPO export')], max_length=32),
        ),
        migrations.AlterField(
            model_name='dsrrequest',
            name='state',
            field=django_fsm.FSMField(choices=[('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted / Under Assessment'), ('DEPT_SEARCH', 'Departmental Search'), ('PRIVACY_REVIEW', 'Privacy Review'), ('LEGAL_REVIEW', 'Legal / Management Review'), ('RESPONSE_PREP', 'Response Preparation'), ('NEEDS_INFORMATION', 'Waiting for Subject Information'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', max_length=32, protected=True),
        ),
    ]
