# Generated by Django 5.2.18 on 2026-10-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0005_source_search_workbench'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsrcaseevent',
            name='event_type',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('TASK_CREATED', 'Review task created'), ('TASK_UPDATED', 'Review task updated'), ('DECISION_RECORDED', 'Decision recorded'), ('PATIENT_UPDATE_RECORDED', 'Patient update recorded'), ('PATIENT_RESPONSE_RECORDED', 'Patient response recorded'), ('CASES_EXPORTED', 'Case included in a DPO export'), ('SOURCE_SEARCH_RECORDED', 'Source search recorded'), ('RESPONSE_FINALIZED', 'Response finalized'), ('RESPONSE_PUBLISHED', 'Response published to portal')], max_length=32),
        ),
        migrations.CreateModel(
            name='DSRResponseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('case_snapshot', models.JSONField(default=dict)),
                ('finalized_by', models.CharField(max_length=128)),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
                ('dsr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_versions', to='dsr.dsrrequest')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='DSRResponsePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_by', models.CharField(max_length=128)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('response_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='dsr.dsrresponseversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dsrresponseversion',
            constraint=models.UniqueConstraint(fields=('dsr', 'version'), name='unique_dsr_response_version'),
        ),
    ]
